const paragraphs = [
    "TYFDSAZXCVERTYUIOPLKJHNMQWERTYLKJH",
    "GFD$AZXCVBN@QWERTYUIO#LKJHGFDS&BNMQWERTYUIO!HGFDSAZXCVB%",
    "UIOPLKJH*CVBNMQW*YUIOPL(JHGFDSAZXCVBNMQWE)YUIOPLKJHGF$SA",
    "Alchemy, Velocity, Ponder, Whimsical, Jargon, Zephyr,  Hypnosis, Serendipity",
    "Horizon, Mirage, Constellation, Tranquil, Echo, Lucid, Phosphorescent, Mosaic,Dynamo",
    "Jovial, Kale, Labyrinthine, Memento, Nebulous, Obelisk, Paladin, Quasar, Resonant,Whimbrel",
    "From a young age, Kalyan was fascinated by the wonders of nature and the mysteries of the stars. He spent countless night lying on the rooftop of his modest home",
    "A baby is a shingle from the right perspective. Before defenses, collars were only operations. Bails are gleesome relatives. An alloy is a streetcar's debt.",
    "A broadband jam is a network of the mind. One cannot separate chickens from glowing periods. A production is a faucet from the right perspective. The lines could be said to resemble zincoid females.",
    "In recent years, some teeming herons are thought of simply as numbers. Nowhere is it disputed that an unlaid fur is a marble of the mind. Far from the truth, few can name a glossy lier that isn't an ingrate bone.",
    "A tramp is a siamese from the right perspective. We know that a flitting monkey's jaw comes with it the thought that the submersed break is a pamphlet. Their cream was, in this moment, a seedy daffodil. The nest is a visitor. Far from the truth,",
    "A cough is a talk from the right perspective. A designed tractor's tray comes with it the thought that the snuffly flax is a rainbow. Their health was, in this moment, an earthy passbook. This could be, or perhaps the swordfishes could be said to resemble healthy sessions.",
    "Authors often misinterpret the flag as a wayless trigonometry, when in actuality it feels more like a bousy gold. Few can name a jasp oven that isn't a stutter grape. They were lost without the huffy religion that composed their booklet. Those waves are nothing more than pedestrians.",
    "This could be, or perhaps few can name a pasteboard quiver that isn't a brittle alligator. A swordfish is a death's numeric. Authors often misinterpret the mist as a swelling asphalt, when in actuality it feels more like a crosswise closet. Some posit the tonal brother-in-law to be less than newborn.", 
    "The frosts could be said to resemble backstage chards. One cannot separate colleges from pinkish bacons. Far from the truth, the mom of a rooster becomes a chordal hydrogen. A tempo can hardly be considered a purer credit without also being a pajama. The first combined ease is, in its own way, a pantyhose.",
];
