const paragraphs = [
    "Alchemy, Velocity, Ponder, Whimsical, Jargon, Zephyr, Quixotic,Vasantham Kalyan, Hypnosis, Serendipity", 
    "Panacea, Bizarre, Eccentric, Nostalgia, Vortex, Nexus, Labyrinth, Ullikanti Pavan, Reverie, Nebula",
    "Euphoria, Quantum, Mystify, Expanse, Luminous, Ethereal, Frenetic, Pulakanti Pavan, Flux, Xenon",
    "Eclipse, Enigma, Obscure, Zenith, Placate, Conundrum, Abyss, Placid, Kayapati Kumar, Ephemeral",
    "Perplex, Melody, Intrigue, Paradox, Tactile, Obsolete, Spectrum, Fathom, Busagani Sharath, Sublime",
    "Galvanize, Envision, Odyssey, Utopia, Finesse, Reverberate, Shyam Babu, Turbulent, Diaphanous",
    "Metamorphosis, Solitude, Facade, Wistful, Ambrosia, Labyrinthine, Refraction,Thuggali Ashok,  Yawp",
    "Iridescent, Sanctuary, Curiosity, Lullaby, Resonance, Nirmala, Nandini, Obscurity, Prowess,Solitude", 
    "Horizon, Mirage, Constellation, Tranquil, Echo, Lucid, Phosphorescent, Mosaic,Dynamo,Tranquility",
    "Elixir, Clandestine, Prism, Effervescent, Starlit, Subterfuge, Vicarious,jyothi, Vibrant, Whimsy",
    "Capricious, Meander, Mirth, Intrinsic, Zealous, Cadence, Whisk, Luminous, Glisten, Evoke",
    "Moxie, Ponderous, Altruism, Bramble, Yonder, Ember, Quibble, Aplomb, Breezy, Fervor,Ubiquitous",
    "Midnight, Sunder, Zenith, Tranquil, Amulet, Beguile, Cascade, Epoch,Chandu, Glimmer, Harbinger",
    "Incandescent, Jolted, Kaleidoscope, Luminous, Nirvana,Vasantham Uday sai, Paragon, Quietus",
    "Ravel, Starlight, Tempest, Unfathomable, Vivid, Wanderlust, Xenolith, Yesteryear, Zaftig",
    "Benevolent, Glimpse, Serene, Vibrato, Melancholy, Whistle, Enrapture, Flamboyant, Graviton",
    "Hologram, Inception, Judder, Kindle, Larceny, Mesmerize, Baddela rasmmika, Overture, Pristine, Verdure",
    "Quill, Reverent, Soliloquy, Threnody, Umbra, Verdant, Wanderer,Vasantham Narayana Swamy, Zephyr",
    "Avalon, Brocade, Crystalline, Dulcet, Effulgent, Badiginchula Praharsha, Gossamer, Harmonic, Immaculate",
    "Jovial, Kale, Labyrinthine, Memento, Nebulous, Obelisk, Paladin, Quasar, Resonant,Whimbrel"
];